_BASE_: "Base-CenterNet.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # WEIGHTS: 'https://download.pytorch.org/models/resnet50-19c8e357.pth'
  WEIGHTS: ""
  MASK_ON: False
  RESNETS:
    DEPTH: 18
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

SOLVER:
  STEPS: (81000, 108000)
  MAX_ITER: 126000
