_BASE_: "Base-CenterNet.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # WEIGHTS: 'https://download.pytorch.org/models/resnet50-19c8e357.pth'
  WEIGHTS: ''
  MASK_ON: False
  RESNETS:
    DEPTH: 50